[package]
authors = ["Scott Godwin <sgodwincs@gmail.com>"]
description = "A WebIDL parser"
homepage = "https://github.com/sgodwincs/webidl-parser"
license = "MIT"
name = "webidl-parser"
readme = "README.md"
repository = "https://github.com/sgodwincs/webidl-parser"
version = "0.1.0"

[dependencies]
clippy = {version = "*", optional = true}

[features]
default = []
