[package]
authors = ["Scott Godwin <sgodwincs@gmail.com>"]
build = "build.rs"
description = "A WebIDL parser"
homepage = "https://github.com/sgodwincs/webidl-rs"
license = "MIT"
name = "webidl"
readme = "README.md"
repository = "https://github.com/sgodwincs/webidl-rs"
version = "0.3.2"

[build-dependencies]
lalrpop = "0.13.1"

[dependencies]
lalrpop-util = "0.13.1"

[dependencies.clippy]
optional = true
version = "0.0.165"

[dev-dependencies]
zip = "0.2.6"

[features]
default = []
