[package]
authors = ["Scott Godwin <sgodwincs@gmail.com>"]
build = "build.rs"
description = "A WebIDL parser"
homepage = "https://github.com/sgodwincs/webidl-parser"
license = "MIT"
name = "webidl-parser"
readme = "README.md"
repository = "https://github.com/sgodwincs/webidl-parser"
version = "0.1.0"

[build-dependencies]
lalrpop = "0.13.0"

[dependencies]
lalrpop-util = "0.13.0"

[dependencies.clippy]
optional = true
version = "*"

[features]
default = []
